http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  post:
    host: localhost
    path: ['/post','/post/*']
  comment:
    host: localhost
    path: ['/comment','/comment/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  postService: 
    url: 'http://localhost:1000'
  commentService:
    url: 'http://localhost:7000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  postPipeline:
    apiEndpoints:
      - post
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: postService 
              changeOrigin: true
  commentPipeline:
    apiEndpoints:
      - comment
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: commentService 
              changeOrigin: true
